grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
